import { IconSun, IconCloud, IconCloudFog, IconCloudRain, IconCloudSnow } from "@tabler/icons-react";
import { JSX } from "react";

export const weatherCodeMap: Record<string, { label: string; icon: (size?: number) => JSX.Element }> = {
  CLEAR_SKY: { label: "Clear sky", icon: (size = 32) => <IconSun className="text-yellow-400" size={size} /> },
  MAINLY_CLEAR: { label: "Mainly clear", icon: (size = 32) => <IconCloud className="text-blue-400" size={size} /> },
  PARTLY_CLOUDY: { label: "Partly cloudy", icon: (size = 32) => <IconCloud className="text-blue-400" size={size} /> },
  OVERCAST: { label: "Overcast", icon: (size = 32) => <IconCloud className="text-blue-400" size={size} /> },
  FOG: { label: "Fog", icon: (size = 32) => <IconCloudFog className="text-gray-400" size={size} /> },
  DEPOSITING_RIME_FOG: { label: "Depositing rime fog", icon: (size = 32) => <IconCloudFog className="text-gray-400" size={size} /> },
  DRIZZLE_LIGHT: { label: "Drizzle", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  DRIZZLE_MODERATE: { label: "Drizzle", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  DRIZZLE_DENSE: { label: "Drizzle", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  FREEZING_DRIZZLE_LIGHT: { label: "Freezing Drizzle: Light", icon: (size = 32) => <IconCloudRain className="text-blue-200" size={size} /> },
  FREEZING_DRIZZLE_DENSE: { label: "Freezing Drizzle: Dense", icon: (size = 32) => <IconCloudRain className="text-blue-200" size={size} /> },
  RAIN_SLIGHT: { label: "Rain", icon: (size = 32) => <IconCloudRain className="text-blue-600" size={size} /> },
  RAIN_MODERATE: { label: "Rain", icon: (size = 32) => <IconCloudRain className="text-blue-600" size={size} /> },
  RAIN_HEAVY: { label: "Rain", icon: (size = 32) => <IconCloudRain className="text-blue-600" size={size} /> },
  FREEZING_RAIN_LIGHT: { label: "Freezing Rain: Light", icon: (size = 32) => <IconCloudRain className="text-blue-200" size={size} /> },
  FREEZING_RAIN_HEAVY: { label: "Freezing Rain: Heavy", icon: (size = 32) => <IconCloudRain className="text-blue-200" size={size} /> },
  SNOW_SLIGHT: { label: "Snow fall: Slight", icon: (size = 32) => <IconCloudSnow className="text-blue-200" size={size} /> },
  SNOW_MODERATE: { label: "Snow fall: Moderate", icon: (size = 32) => <IconCloudSnow className="text-blue-200" size={size} /> },
  SNOW_HEAVY: { label: "Snow fall: Heavy", icon: (size = 32) => <IconCloudSnow className="text-blue-200" size={size} /> },
  SNOW_GRAINS: { label: "Snow grains", icon: (size = 32) => <IconCloudSnow className="text-blue-200" size={size} /> },
  RAIN_SHOWERS_SLIGHT: { label: "Rain showers: Slight", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  RAIN_SHOWERS_MODERATE: { label: "Rain showers: Moderate", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  RAIN_SHOWERS_VIOLENT: { label: "Rain showers: Violent", icon: (size = 32) => <IconCloudRain className="text-blue-400" size={size} /> },
  SNOW_SHOWERS_SLIGHT: { label: "Snow showers: Slight", icon: (size = 32) => <IconCloudSnow className="text-blue-400" size={size} /> },
  SNOW_SHOWERS_HEAVY: { label: "Snow showers: Heavy", icon: (size = 32) => <IconCloudSnow className="text-blue-400" size={size} /> },
  THUNDERSTORM_SLIGHT_MODERATE: { label: "Thunderstorm: Slight or moderate", icon: (size = 32) => <IconCloud className="text-yellow-600" size={size} /> },
  THUNDERSTORM_SLIGHT_HAIL: { label: "Thunderstorm with slight hail", icon: (size = 32) => <IconCloudSnow className="text-blue-400" size={size} /> },
  THUNDERSTORM_HEAVY_HAIL: { label: "Thunderstorm with heavy hail", icon: (size = 32) => <IconCloudSnow className="text-blue-400" size={size} /> },
};
